INSERT INTO git_commands (command, category, description, example) VALUES
('git init', 'Basics', 'Initializes a new Git repository', 'git init'),
('git clone', 'Basics', 'Clones a repository into a new directory', 'git clone https://github.com/user/repo.git'),
('git status', 'Basics', 'Displays the status of the working directory and staging area', 'git status'),
('git add', 'Staging', 'Adds file contents to the staging area', 'git add filename.txt'),
('git commit', 'Staging', 'Records changes to the repository', 'git commit -m "Initial commit"'),
('git push', 'Remote', 'Uploads local commits to the remote repository', 'git push origin main'),
('git pull', 'Remote', 'Fetches and integrates changes from the remote repo', 'git pull origin main'),
('git fetch', 'Remote', 'Downloads objects and refs from another repository', 'git fetch origin'),
('git branch', 'Branching', 'Lists, creates, or deletes branches', 'git branch new-feature'),
('git checkout', 'Branching', 'Switches branches or restores files', 'git checkout main'),
('git merge', 'Branching', 'Joins two or more development histories together', 'git merge new-feature'),
('git rebase', 'Branching', 'Reapplies commits on top of another base tip', 'git rebase main'),
('git log', 'Logs', 'Shows the commit logs', 'git log'),
('git diff', 'Changes', 'Shows changes between commits, branches, etc.', 'git diff HEAD~1 HEAD'),
('git reset', 'Changes', 'Resets current HEAD to the specified state', 'git reset --hard HEAD~1'),
('git rm', 'Staging', 'Removes files from the working directory and staging area', 'git rm file.txt'),
('git mv', 'Staging', 'Moves or renames a file', 'git mv old.txt new.txt'),
('git config', 'Config', 'Sets configuration values', 'git config --global user.name "Your Name"'),
('git remote', 'Remote', 'Manages set of tracked repositories', 'git remote -v'),
('git tag', 'Versioning', 'Tags specific commits in history', 'git tag v1.0'),
('git stash', 'Changes', 'Stashes changes in a dirty working directory', 'git stash'),
('git stash apply', 'Changes', 'Applies previously stashed changes', 'git stash apply'),
('git cherry-pick', 'Branching', 'Applies the changes introduced by existing commits', 'git cherry-pick abc123'),
('git show', 'Logs', 'Shows various types of objects', 'git show abc123'),
('git blame', 'Logs', 'Shows who changed what and when in a file', 'git blame main.java'),
('git clean', 'Changes', 'Removes untracked files from the working directory', 'git clean -f'),
('git reflog', 'Logs', 'Shows the history of HEAD changes', 'git reflog'),
('git archive', 'Utilities', 'Creates an archive of files from a named tree', 'git archive --format=zip HEAD > latest.zip'),
('git bisect', 'Debugging', 'Helps find the commit that introduced a bug', 'git bisect start'),
('git shortlog', 'Logs', 'Summarizes git log output', 'git shortlog'),
('git grep', 'Search', 'Searches for a string in tracked files', 'git grep "search-term"'),
('git init --bare', 'Basics', 'Creates a bare Git repository (for server hosting)', 'git init --bare'),
('git checkout -b', 'Branching', 'Creates and switches to a new branch', 'git checkout -b feature-x'),
('git merge --no-ff', 'Branching', 'Forces a merge commit even if fast-forward is possible', 'git merge --no-ff feature-x'),
('git push --force', 'Remote', 'Forcibly pushes changes (use with caution)', 'git push --force'),
('git pull --rebase', 'Remote', 'Pulls changes using rebase instead of merge', 'git pull --rebase origin main'),
('git revert', 'Changes', 'Reverts a previous commit', 'git revert abc123'),
('git log --oneline', 'Logs', 'Shows compact log output', 'git log --oneline'),
('git log --graph', 'Logs', 'Shows a graphical representation of commits', 'git log --graph --oneline'),
('git commit --amend', 'Staging', 'Modifies the most recent commit', 'git commit --amend'),
('git diff --cached', 'Changes', 'Shows differences in the staged area', 'git diff --cached'),
('git reset --soft', 'Changes', 'Moves HEAD but preserves staged changes', 'git reset --soft HEAD~1'),
('git reset --mixed', 'Changes', 'Moves HEAD and unstages changes', 'git reset --mixed HEAD~1'),
('git remote add', 'Remote', 'Adds a new remote repository', 'git remote add origin https://github.com/user/repo.git'),
('git remote remove', 'Remote', 'Removes a remote repository', 'git remote remove origin'),
('git config --list', 'Config', 'Lists all Git configuration settings', 'git config --list'),
('git stash list', 'Changes', 'Lists stashed changes', 'git stash list'),
('git stash pop', 'Changes', 'Applies and removes the latest stash', 'git stash pop'),
('git help', 'Basics', 'Displays help information about Git', 'git help status');
